server:
  port: 8000
  servlet:
    context-path: /
spring:
  application:
    name: ecmp-customer-mock
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  freemarker:
    cache: false
    charset : UTF-8
    suffix: .html
mybatis:
  mapper-locations:    classpath*:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://cmp-mysql.res.yqxiu.cn:3306/ecmp_mock?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ecmp_mock
    password: UW1llBvv3lc0meD

mock:
  server: https://stz.eqshow.cn/
  #http://mock.yqxiu.cn
  #https://stz.eqshow.cn/
  #https://open.eqshow.cn

  batchUrl: http://172.16.21.196:8999/ecmp/test/batch/excute
  open-id: eqixiu666666
  #batchUrl: http://127.0.0.1:8999/ecmp/test/batch/excute

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://cmp-mysql.res.yqxiu.cn:3306/ecmp_mock?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ecmp_mock
    password: UW1llBvv3lc0meD
    driver-class-name: com.mysql.cj.jdbc.Driver

mock:
  batchUrl: http://172.16.21.196:8999/ecmp/test/batch/excute
  server: https://open.eqxiu.cn
  open-id: eqixiu666666